model_name: meta-llama/Llama-3.1-8B
editor:
  type: FineTuning
  trainable_pattern: '.'
  opt_name: AdamW
  opt_kwargs:
    lr: 1e-5
    weight_decay: 0.0
  minibatch_tokens: 4096
  steps: 25
  early_stop: 0.015
  train_mode: True
  