model_name: meta-llama/Llama-3.1-8B
preprocess: stanford_openie
simplification: SimplificationWrapper
editor:
  type: MENDWrapper
  model_dir: ./baselines/mend/weights
  hparams: {
    "lr_scale": 1.0,
    "n_toks": 10,
    "model_name": "meta-llama/Llama-3.1-8B",
    "counterfact": false,
    "zsre": true,
    "mini": false
  }
  model_filename: Llama-3.1-8B