model_name: EleutherAI/gpt-j-6B
editor:
  type: EvoEdit
  trainable_pattern: '.'
  opt_name: AdamW
  opt_kwargs:
    lr: 4e-5
    weight_decay: 0.01
  minibatch_tokens: 4096
  steps: 25
  early_stop: 0.1
  train_mode: True
  importance_ratio: 0.2
merge_weight: 0.35+0.15+0.5
noise_alpha: 32