model_name: meta-llama/Llama-2-7b-hf
editor:
  type: EvoEdit
  trainable_pattern: '.'
  opt_name: AdamW
  opt_kwargs:
    lr: 3e-5
    weight_decay: 0.00
  minibatch_tokens: 4096
  steps: 25
  early_stop: 0.1
  train_mode: True
  importance_ratio: 0.2
merge_weight: 0.25+0.25+0.5
noise_alpha: 32